import subprocess
import time

subprocess.Popen(["python3","e1.py"])
time.sleep(120)
subprocess.Popen(["python3","e2.py"])
time.sleep(120)
subprocess.Popen(["python3","e3.py"])
time.sleep(120)
subprocess.Popen(["python3","e4.py"])
time.sleep(120)
subprocess.Popen(["python3","e5.py"])
time.sleep(120)
subprocess.Popen(["python3","e6.py"])
time.sleep(120)
subprocess.Popen(["python3","e7.py"])
time.sleep(120)
subprocess.Popen(["python3","e8.py"])
time.sleep(120)
subprocess.Popen(["python3","e9.py"])
time.sleep(120)
subprocess.Popen(["python3","e10.py"])
